[package]
name = "servos"
version = "0.1.0"
edition = "2021"

[dependencies]
concat-idents = "1.1.5"
lock_api = "0.4.12"
spin = "0.9.8"

[dependencies.fdt-rs]
version = "0.4.5"
default-features = false

[dependencies.arrayvec]
version = "0.7.4"
default-features = false
