[package]
name = "userstd"
version = "0.1.0"
edition = "2021"

[dependencies]
linked_list_allocator = { version = "0.10.5", default-features = false }
shared = { path = "../../shared", features = [] }
