[build]
target = "riscv64imac-unknown-none-elf"
target-dir = "target"

[target.riscv64imac-unknown-none-elf]
runner = "qemu-system-riscv64 -machine virt -m 128M -s -nographic -serial mon:stdio -bios"
